#!/bin/bash

# instalar cenas
apt-get update
apt-get install vim git flex gawk -y

# compilar com cores
wget https://raw.github.com/colorgcc/colorgcc/master/colorgcc.pl
chmod +x colorgcc.pl
sudo mv colorgcc.pl /usr/local/bin/gcc

# configurar o git
git config --global color.ui true
echo "DON'T FORGET TO RUN THESE COMMANDS:"
echo "git config --global user.name \"My Name\""
echo "git config --global user.email my@email.example"
